{{- if .Values.app.grpcServerEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orkes-conductor.fullname" . }}-grpc
  labels:
    serviceName: {{ include "orkes-conductor.fullname" . }}-grpc
    {{- include "orkes-conductor.labels" . | nindent 4 }}-grpc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      protocol: TCP
      targetPort: 8090
      name: default-grpc-port
  selector:
    {{- include "orkes-conductor.selectorLabels" . | nindent 4 }}
{{- end -}}
