apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orkes-conductor-community.fullname" . }}
  labels:
    {{- include "orkes-conductor-community.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orkes-conductor-community.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        {{- include "orkes-conductor-community.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
          - name: cloud.env
            value: gcp
          - name: conductor.redis-lock.serverAddress
            value: redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}
          - name: SPRING_PROFILES_ACTIVE
            value: logrotate
          - name: spring.datasource.password
            value: {{ .Values.postgres.password | quote }}
          - name: spring.datasource.username
            value: {{ .Values.postgres.username | quote }}
          - name: spring.datasource.url
            value: {{ .Values.postgres.url | quote }}
          - name: DEPLOY_ENV
            value: prod
          - name: conductor.redis.hosts
            value: {{ .Values.redis.host }}:{{ .Values.redis.port }}:us-east-1c
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: orkes-conductor-community
          ports:
            - name: liveness-port
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.app.resources.cpuLimit | quote }}
              memory: {{ .Values.app.resources.memoryLimit | quote }}
            requests:
              cpu: {{ .Values.app.resources.cpuRequests | quote }}
              memory: {{ .Values.app.resources.memoryRequests | quote }}
          startupProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: orkesregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30